"""Initial migrate

Revision ID: b0619e6f0329
Revises: 
Create Date: 2020-07-30 13:31:09.079292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0619e6f0329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cumulative_result',
    sa.Column('google_id', sa.String(length=30), nullable=False),
    sa.Column('times', sa.Integer(), nullable=False),
    sa.Column('cumulative_count', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('google_id', 'kind'),
    sa.UniqueConstraint('google_id', 'kind')
    )
    op.create_table('total_results',
    sa.Column('google_id', sa.String(length=30), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('google_id', 'time'),
    sa.UniqueConstraint('google_id', 'time')
    )
    op.create_table('user',
    sa.Column('google_id', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('google_id'),
    sa.UniqueConstraint('google_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('total_results')
    op.drop_table('cumulative_result')
    # ### end Alembic commands ###
