"""adjust kind

Revision ID: 8b28c9d35577
Revises: 8d0ec655d971
Create Date: 2020-10-29 20:07:21.967544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b28c9d35577'
down_revision = '8d0ec655d971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    op.drop_column('user', 'height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
