"""adjust kind

Revision ID: 61a293ff5b8e
Revises: 8d0ec655d971
Create Date: 2020-11-07 12:22:19.799348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61a293ff5b8e'
down_revision = '8d0ec655d971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cumulative_result', sa.Column('kind', sa.String(length=5), nullable=False))
    op.drop_column('cumulative_result', 'type')
    op.add_column('total_results', sa.Column('kind', sa.String(length=5), nullable=False))
    op.drop_column('total_results', 'type')
    op.drop_column('user', 'height')
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('total_results', sa.Column('type', mysql.VARCHAR(length=5), nullable=False))
    op.drop_column('total_results', 'kind')
    op.add_column('cumulative_result', sa.Column('type', mysql.VARCHAR(length=5), nullable=False))
    op.drop_column('cumulative_result', 'kind')
    # ### end Alembic commands ###
