"""add attribute in user

Revision ID: 8d0ec655d971
Revises: b0619e6f0329
Create Date: 2020-10-27 12:19:18.065181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0ec655d971'
down_revision = 'b0619e6f0329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('google_id', table_name='cumulative_result')
    op.drop_index('google_id', table_name='total_results')
    op.add_column('user', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    op.drop_index('google_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('google_id', 'user', ['google_id'], unique=True)
    op.drop_column('user', 'weight')
    op.drop_column('user', 'height')
    op.create_index('google_id', 'total_results', ['google_id', 'time'], unique=True)
    op.create_index('google_id', 'cumulative_result', ['google_id', 'kind'], unique=True)
    # ### end Alembic commands ###
